import type { Product, Member, Order, Bundle } from "./types";

const NOW = new Date("2026-04-27T08:00:00Z").toISOString();

/**
 * Real Elevations247 catalogue, sourced from:
 *   SX-2026-04-ELV-PRICING-v0.1 (Pricing + Stock + Margin sheets)
 *   Stock-on-hand as at 27 April 2026.
 *
 * Bundle ladders (per pricing sheet):
 *   Greenhouse flower & preroll  R100 / R185 / R265   (save R15 / R35)
 *   Tunnel flower                R100 / R185 / —      (save R15)
 *   Indoor flower & preroll      R150 / R280 / R400   (save R20 / R50)
 *   Hydro flower & preroll       R175 / R325 / R480   (save R25 / R45)
 *   Indoor moonstick             R200 / R370 / —      (save R30)
 *   Greenhouse moonstick         R150 / R280 / —      (save R20)
 *   Reina Vape                   R750                 (per unit, no ladder)
 */

const FLOWER_BUNDLES = {
  greenhouse: [
    { qty: 1, label: "1g", price: 100 },
    { qty: 2, label: "2g", price: 185, saving: 15 },
    { qty: 3, label: "3g", price: 265, saving: 35 },
  ] as Bundle[],
  tunnel: [
    { qty: 1, label: "1g", price: 100 },
    { qty: 2, label: "2g", price: 185, saving: 15 },
  ] as Bundle[],
  indoor: [
    { qty: 1, label: "1g", price: 150 },
    { qty: 2, label: "2g", price: 280, saving: 20 },
    { qty: 3, label: "3g", price: 400, saving: 50 },
  ] as Bundle[],
  hydro: [
    { qty: 1, label: "1g", price: 175 },
    { qty: 2, label: "2g", price: 325, saving: 25 },
    { qty: 3, label: "3g", price: 480, saving: 45 },
  ] as Bundle[],
};

const MOONSTICK_BUNDLES = {
  indoor: [
    { qty: 1, label: "1 unit", price: 200 },
    { qty: 2, label: "2 units", price: 370, saving: 30 },
  ] as Bundle[],
  greenhouse: [
    { qty: 1, label: "1 unit", price: 150 },
    { qty: 2, label: "2 units", price: 280, saving: 20 },
  ] as Bundle[],
};

export const SEED_PRODUCTS: Product[] = [
  // ─── Indoor Bud ─────────────────────────────────────────────────────
  {
    id: "p_banana_knuckles",
    name: "Banana Knuckles",
    category: "flower",
    grade: "Indoor",
    type: "hybrid",
    thc_percent: 22.0,
    cbd_percent: 0.3,
    effects: ["Sweet", "Calm", "Happy"],
    terpenes: ["Limonene", "Caryophyllene", "Myrcene"],
    description:
      "Tropical and creamy on the inhale, settling into a smooth banana finish. A balanced indoor hybrid for any time of day.",
    image_url: "/assets/products/banana-knuckles.jpg",
    retail_price: 150,
    cost_price: 45,
    unit_label: "g",
    bundles: FLOWER_BUNDLES.indoor,
    stock_qty: 40.73,
    status: "in_stock",
    display_order: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "p_exo_cheese",
    name: "Exo Cheese",
    category: "flower",
    grade: "Indoor",
    type: "indica",
    thc_percent: 24.0,
    cbd_percent: 0.4,
    effects: ["Relaxed", "Sleepy", "Funky"],
    terpenes: ["Myrcene", "Caryophyllene", "Humulene"],
    description:
      "Aged-cheese funk over a deeply relaxing indica body. Hand-trimmed and slow-cured. Best after dark.",
    image_url: "/assets/products/exo-cheese.jpg",
    retail_price: 150,
    cost_price: 45,
    unit_label: "g",
    bundles: FLOWER_BUNDLES.indoor,
    stock_qty: 37.16,
    status: "in_stock",
    display_order: 2,
    created_at: NOW,
    updated_at: NOW,
  },

  // ─── Hydro Bud ──────────────────────────────────────────────────────
  {
    id: "p_blue_pave",
    name: "Blue Pave",
    category: "flower",
    grade: "Hydro",
    type: "hybrid",
    thc_percent: 24.0,
    cbd_percent: 0.2,
    effects: ["Blueberry", "Smooth", "Refined"],
    terpenes: ["Linalool", "Myrcene", "Pinene"],
    description:
      "A signature hydro hybrid — wild blueberry on the nose, glassy resin coverage, and a long, easy finish.",
    image_url: "/assets/products/blue-pave.jpg",
    retail_price: 175,
    cost_price: 70,
    unit_label: "g",
    bundles: FLOWER_BUNDLES.hydro,
    stock_qty: 57.87,
    status: "in_stock",
    display_order: 3,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "p_moch_1",
    name: "Moch 1",
    category: "flower",
    grade: "Hydro",
    type: "hybrid",
    thc_percent: 25.5,
    cbd_percent: 0.2,
    effects: ["Mocha", "Rich", "Cerebral"],
    terpenes: ["Caryophyllene", "Limonene", "Humulene"],
    description:
      "A roasted-coffee, cocoa-edged hydro selection. Limited stock — a connoisseur's pick.",
    image_url: "/assets/products/moch-1.jpg",
    retail_price: 175,
    cost_price: 70,
    unit_label: "g",
    bundles: FLOWER_BUNDLES.hydro,
    stock_qty: 16.0,
    status: "in_stock",
    display_order: 4,
    created_at: NOW,
    updated_at: NOW,
  },

  // ─── Tunnel Bud ─────────────────────────────────────────────────────
  {
    id: "p_death_by_truffles",
    name: "Death by Truffles",
    category: "flower",
    grade: "Tunnel",
    type: "indica",
    thc_percent: 23.0,
    cbd_percent: 0.3,
    effects: ["Earthy", "Heavy", "Calm"],
    terpenes: ["Myrcene", "Caryophyllene"],
    description:
      "Dense, gas-forward tunnel-grown indica. Earth and dark-truffle notes — for slow evenings.",
    image_url: "/assets/products/death-by-truffles.jpg",
    retail_price: 100,
    cost_price: 30,
    unit_label: "g",
    bundles: FLOWER_BUNDLES.tunnel,
    stock_qty: 48.96,
    status: "in_stock",
    display_order: 5,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "p_higher_primate",
    name: "Higher Primate",
    category: "flower",
    grade: "Tunnel",
    type: "hybrid",
    thc_percent: 22.0,
    cbd_percent: 0.2,
    effects: ["Uplifting", "Sweet", "Social"],
    terpenes: ["Limonene", "Pinene", "Myrcene"],
    description:
      "A bright, sociable tunnel hybrid — sweet on the inhale, clear-headed on the way down.",
    image_url: "/assets/products/higher-primate.jpg",
    retail_price: 100,
    cost_price: 30,
    unit_label: "g",
    bundles: FLOWER_BUNDLES.tunnel,
    stock_qty: 52.91,
    status: "in_stock",
    display_order: 6,
    created_at: NOW,
    updated_at: NOW,
  },

  // ─── Greenhouse Bud ─────────────────────────────────────────────────
  {
    id: "p_malawi_gold",
    name: "Malawi Gold",
    category: "flower",
    grade: "Greenhouse",
    type: "sativa",
    thc_percent: 18.0,
    cbd_percent: 0.4,
    effects: ["Bright", "Spicy", "Energetic"],
    terpenes: ["Pinene", "Terpinolene", "Limonene"],
    description:
      "A heritage African sativa, sun-grown in greenhouse conditions. Spicy, golden, and lifting.",
    image_url: "/assets/products/malawi-gold.jpg",
    retail_price: 100,
    cost_price: 20,
    unit_label: "g",
    bundles: FLOWER_BUNDLES.greenhouse,
    stock_qty: 96.24,
    status: "in_stock",
    display_order: 7,
    created_at: NOW,
    updated_at: NOW,
  },

  // ─── Indoor Pre-rolls ───────────────────────────────────────────────
  {
    id: "p_pr_mimosa",
    name: "Mimosa",
    category: "preroll",
    grade: "Indoor",
    type: "sativa",
    thc_percent: 20.0,
    cbd_percent: 0.2,
    effects: ["Citrus", "Bright", "Energetic"],
    terpenes: ["Limonene", "Pinene", "Linalool"],
    description:
      "Sparkling citrus sativa, hand-rolled in unbleached paper. Lights even, draws clean.",
    image_url: "/assets/products/preroll-mimosa.jpg",
    retail_price: 150,
    cost_price: 35,
    unit_label: "g",
    bundles: FLOWER_BUNDLES.indoor,
    stock_qty: 26.0,
    status: "in_stock",
    display_order: 8,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "p_pr_white_widow",
    name: "White Widow",
    category: "preroll",
    grade: "Indoor",
    type: "hybrid",
    thc_percent: 20.0,
    cbd_percent: 0.3,
    effects: ["Balanced", "Focused", "Happy"],
    terpenes: ["Myrcene", "Pinene", "Linalool"],
    description:
      "A frosted classic, hand-rolled. Balanced, dependable, equally at home morning or evening.",
    image_url: "/assets/products/preroll-white-widow.jpg",
    retail_price: 150,
    cost_price: 35,
    unit_label: "g",
    bundles: FLOWER_BUNDLES.indoor,
    stock_qty: 30.0,
    status: "in_stock",
    display_order: 9,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "p_pr_purple_urkle",
    name: "Purple Urkle",
    category: "preroll",
    grade: "Indoor",
    type: "indica",
    thc_percent: 21.0,
    cbd_percent: 0.4,
    effects: ["Berry", "Calm", "Sleepy"],
    terpenes: ["Myrcene", "Caryophyllene", "Linalool"],
    description:
      "Deep grape and dark-berry — an indica pre-roll for the slow part of the night.",
    image_url: "/assets/products/preroll-purple-urkle.jpg",
    retail_price: 150,
    cost_price: 35,
    unit_label: "g",
    bundles: FLOWER_BUNDLES.indoor,
    stock_qty: 23.0,
    status: "in_stock",
    display_order: 10,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "p_pr_indoor_house",
    name: "House Indoor Pre-Roll",
    category: "preroll",
    grade: "Indoor",
    type: "hybrid",
    thc_percent: 21.0,
    cbd_percent: 0.3,
    effects: ["Relaxed", "Social", "Easy"],
    terpenes: ["Myrcene", "Caryophyllene"],
    description:
      "A curated indoor blend, hand-rolled. The reliable everyday choice.",
    image_url: "/assets/products/preroll-house-indoor.jpg",
    retail_price: 150,
    cost_price: 35,
    unit_label: "g",
    bundles: FLOWER_BUNDLES.indoor,
    stock_qty: 20.0,
    status: "in_stock",
    display_order: 11,
    created_at: NOW,
    updated_at: NOW,
  },

  // ─── Hydro Pre-roll ─────────────────────────────────────────────────
  {
    id: "p_pr_dark_horse_amnesia",
    name: "Dark Horse Amnesia",
    category: "preroll",
    grade: "Hydro",
    type: "sativa",
    thc_percent: 22.0,
    cbd_percent: 0.2,
    effects: ["Haze", "Citrus", "Uplifting"],
    terpenes: ["Limonene", "Pinene", "Terpinolene"],
    description:
      "A bright haze sativa pre-roll, rolled from hydro flower. Long, clear-headed lift.",
    image_url: "/assets/products/preroll-dark-horse-amnesia.jpg",
    retail_price: 175,
    cost_price: 50,
    unit_label: "g",
    bundles: FLOWER_BUNDLES.hydro,
    stock_qty: 36.0,
    status: "in_stock",
    display_order: 12,
    created_at: NOW,
    updated_at: NOW,
  },

  // ─── Greenhouse Pre-roll ────────────────────────────────────────────
  {
    id: "p_pr_greenhouse_house",
    name: "House Greenhouse Pre-Roll",
    category: "preroll",
    grade: "Greenhouse",
    type: "hybrid",
    thc_percent: 18.0,
    cbd_percent: 0.4,
    effects: ["Easy", "Mellow", "Light"],
    terpenes: ["Myrcene", "Pinene"],
    description:
      "Sun-grown greenhouse hybrid, hand-rolled. Easy on the lungs, easy on the wallet.",
    image_url: "/assets/products/preroll-house-greenhouse.jpg",
    retail_price: 100,
    cost_price: 18,
    unit_label: "g",
    bundles: FLOWER_BUNDLES.greenhouse,
    stock_qty: 105.0,
    status: "in_stock",
    display_order: 13,
    created_at: NOW,
    updated_at: NOW,
  },

  // ─── Moonsticks ─────────────────────────────────────────────────────
  {
    id: "p_ms_indoor",
    name: "Indoor Moonstick",
    category: "moonstick",
    grade: "Indoor",
    type: "hybrid",
    thc_percent: 50.0,
    cbd_percent: 0.5,
    effects: ["Heavy", "Concentrated", "Euphoric"],
    terpenes: ["Myrcene", "Caryophyllene"],
    description:
      "Indoor flower hand-coated in concentrate and rolled in kief. Slow and intentional — one is enough.",
    image_url: "/assets/products/moonstick-indoor.jpg",
    retail_price: 200,
    cost_price: 75,
    unit_label: "unit",
    bundles: MOONSTICK_BUNDLES.indoor,
    stock_qty: 8,
    status: "in_stock",
    display_order: 14,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "p_ms_greenhouse",
    name: "Greenhouse Moonstick",
    category: "moonstick",
    grade: "Greenhouse",
    type: "hybrid",
    thc_percent: 40.0,
    cbd_percent: 0.6,
    effects: ["Heavy", "Smooth", "Calm"],
    terpenes: ["Myrcene", "Linalool"],
    description:
      "Greenhouse flower coated and dusted — softer profile, same intentional finish.",
    image_url: "/assets/products/moonstick-greenhouse.jpg",
    retail_price: 150,
    cost_price: 58,
    unit_label: "unit",
    bundles: MOONSTICK_BUNDLES.greenhouse,
    stock_qty: 10,
    status: "in_stock",
    display_order: 15,
    created_at: NOW,
    updated_at: NOW,
  },

  // ─── Vape ───────────────────────────────────────────────────────────
  {
    id: "p_vape_reina",
    name: "Reina Vape",
    category: "vape",
    grade: "Indoor",
    type: "hybrid",
    thc_percent: 80.0,
    effects: ["Smooth", "Discreet", "Reliable"],
    terpenes: ["Limonene", "Pinene"],
    description:
      "Premium ceramic-core distillate vape. Clean draw, charcoal housing, fully discreet.",
    image_url: "/assets/products/vape-reina.jpg",
    retail_price: 750,
    cost_price: 450,
    unit_label: "unit",
    stock_qty: 8,
    status: "in_stock",
    display_order: 16,
    created_at: NOW,
    updated_at: NOW,
  },
];

export const SEED_GRADES = [
  { id: "g_hydro", label: "Hydro", display_order: 1 },
  { id: "g_indoor", label: "Indoor", display_order: 2 },
  { id: "g_tunnel", label: "Tunnel", display_order: 3 },
  { id: "g_greenhouse", label: "Greenhouse", display_order: 4 },
];

export const SEED_MEMBERS: Member[] = [
  {
    id: "m_001",
    member_id: "082341",
    first_name: "Sasha",
    last_name: "Botha",
    cell: "0823412847",
    email: "sasha@example.co.za",
    id_number: "9504125800087",
    address_street: "12 Dorp Street",
    address_suburb: "Stellenbosch Central",
    address_city: "Stellenbosch",
    referral_source: "Instagram",
    status: "active",
    agreed_to_terms: true,
    created_at: "2026-03-12T18:24:00Z",
    last_active: "2026-04-26T22:11:00Z",
  },
  {
    id: "m_002",
    member_id: "071829",
    first_name: "Liam",
    last_name: "van der Merwe",
    cell: "0718294156",
    email: "liam@example.co.za",
    id_number: "9912055100089",
    address_street: "47 Banhoek Road",
    address_suburb: "Mostertsdrift",
    address_city: "Stellenbosch",
    referral_source: "Word of Mouth",
    status: "active",
    agreed_to_terms: true,
    created_at: "2026-03-21T11:02:00Z",
    last_active: "2026-04-27T07:14:00Z",
  },
  {
    id: "m_003",
    member_id: "076412",
    first_name: "Nadia",
    last_name: "Pretorius",
    cell: "0764127391",
    email: "nadia@example.co.za",
    id_number: "9707085800086",
    address_street: "8 Bird Street",
    address_suburb: "Stellenbosch Central",
    address_city: "Stellenbosch",
    referral_source: "WhatsApp",
    status: "active",
    agreed_to_terms: true,
    created_at: "2026-04-02T19:48:00Z",
    last_active: "2026-04-25T20:52:00Z",
  },
  {
    id: "m_004",
    member_id: "083901",
    first_name: "Kabelo",
    last_name: "Dlamini",
    cell: "0839015627",
    email: "kabelo@example.co.za",
    id_number: "9608225800082",
    address_street: "21 Helderberg Street",
    address_suburb: "Die Boord",
    address_city: "Stellenbosch",
    referral_source: "Instagram",
    status: "active",
    agreed_to_terms: true,
    created_at: "2026-04-10T14:30:00Z",
    last_active: "2026-04-27T06:30:00Z",
  },
  {
    id: "m_005",
    member_id: "072518",
    first_name: "Robyn",
    last_name: "Müller",
    cell: "0725186403",
    email: "robyn@example.co.za",
    id_number: "9802145800082",
    address_street: "5 Plein Street",
    address_suburb: "Universiteitsoord",
    address_city: "Stellenbosch",
    referral_source: "Other",
    status: "active",
    agreed_to_terms: true,
    created_at: "2026-04-15T09:15:00Z",
    last_active: "2026-04-26T11:00:00Z",
  },
];

export const SEED_ORDERS: Order[] = [
  {
    id: "o_001",
    reference: "ELV-00247",
    member_id: "m_001",
    member_name: "Sasha Botha",
    status: "out_for_delivery",
    delivery_address: {
      street: "12 Dorp Street",
      suburb: "Stellenbosch Central",
      city: "Stellenbosch",
    },
    items: [
      { product_id: "p_blue_pave", name: "Blue Pave · 2g", qty: 1, unit_price: 325 },
      { product_id: "p_pr_mimosa", name: "Mimosa · 1g", qty: 1, unit_price: 150 },
    ],
    total_retail: 475,
    total_cost: 175,
    delivery_note: "Driver en route. ETA 25 min.",
    placed_at: "2026-04-27T06:42:00Z",
    updated_at: "2026-04-27T07:38:00Z",
  },
  {
    id: "o_002",
    reference: "ELV-00246",
    member_id: "m_002",
    member_name: "Liam van der Merwe",
    status: "delivered",
    delivery_address: {
      street: "47 Banhoek Road",
      suburb: "Mostertsdrift",
      city: "Stellenbosch",
    },
    items: [
      { product_id: "p_malawi_gold", name: "Malawi Gold · 3g", qty: 1, unit_price: 265 },
    ],
    total_retail: 265,
    total_cost: 60,
    placed_at: "2026-04-26T20:15:00Z",
    updated_at: "2026-04-26T21:10:00Z",
  },
  {
    id: "o_003",
    reference: "ELV-00245",
    member_id: "m_003",
    member_name: "Nadia Pretorius",
    status: "packing",
    delivery_address: {
      street: "8 Bird Street",
      suburb: "Stellenbosch Central",
      city: "Stellenbosch",
    },
    items: [
      { product_id: "p_ms_indoor", name: "Indoor Moonstick · 2 units", qty: 1, unit_price: 370 },
      { product_id: "p_pr_purple_urkle", name: "Purple Urkle · 1g", qty: 1, unit_price: 150 },
    ],
    total_retail: 520,
    total_cost: 185,
    placed_at: "2026-04-27T07:05:00Z",
    updated_at: "2026-04-27T07:30:00Z",
  },
  {
    id: "o_004",
    reference: "ELV-00244",
    member_id: "m_004",
    member_name: "Kabelo Dlamini",
    status: "confirmed",
    delivery_address: {
      street: "21 Helderberg Street",
      suburb: "Die Boord",
      city: "Stellenbosch",
    },
    items: [
      { product_id: "p_vape_reina", name: "Reina Vape", qty: 1, unit_price: 750 },
    ],
    total_retail: 750,
    total_cost: 450,
    placed_at: "2026-04-27T07:22:00Z",
    updated_at: "2026-04-27T07:25:00Z",
  },
  {
    id: "o_005",
    reference: "ELV-00243",
    member_id: "m_005",
    member_name: "Robyn Müller",
    status: "delivered",
    delivery_address: {
      street: "5 Plein Street",
      suburb: "Universiteitsoord",
      city: "Stellenbosch",
    },
    items: [
      { product_id: "p_higher_primate", name: "Higher Primate · 2g", qty: 1, unit_price: 185 },
    ],
    total_retail: 185,
    total_cost: 60,
    placed_at: "2026-04-25T19:18:00Z",
    updated_at: "2026-04-25T20:22:00Z",
  },
];
